name = "CompositionalJulia"
uuid = "b961d7e5-ecbf-469c-9360-98fdded73e0b"
authors = ["A. William Crane"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
